<?php
define('host','localhost');
define('dbname','cloud_lab');
define('username','root');
define('password','');
define('charset','utf-8');
define('tablePrefix','t_');
define('PHPPATH','../main/');
?>